<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => '使用说明',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2019-04-06 14:48:57',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => '媒体',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-08-03 06:53:11',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => '用户',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 1,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-08-03 06:52:26',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => '角色',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 2,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-08-03 06:52:32',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => '工具',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2019-04-06 14:48:57',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => '菜单管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 5,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-09-30 10:41:18',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => '数据库',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 3,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-08-03 06:52:34',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => '指南针',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2019-03-20 00:23:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 4,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-09-30 10:41:18',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => '设置',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 6,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2018-09-30 10:41:18',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2018-06-11 13:51:59',
                'updated_at' => '2019-03-20 00:23:50',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => '课程',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-06-13 13:17:56',
                'updated_at' => '2018-12-18 14:12:30',
                'route' => 'voyager.courses.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => '后台编辑',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-activity',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2018-08-03 06:52:13',
                'updated_at' => '2019-04-06 14:48:57',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => '课题',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-08-20 07:25:57',
                'updated_at' => '2019-02-26 19:07:24',
                'route' => 'voyager.tasks.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => '团队',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-08-21 08:26:14',
                'updated_at' => '2019-02-26 19:07:24',
                'route' => 'voyager.teams.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => '课题申请书',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-12-16 22:01:41',
                'updated_at' => '2019-03-11 22:43:50',
                'route' => 'voyager.requests.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => '课题成果',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-receipt',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-12-18 14:42:12',
                'updated_at' => '2019-03-11 22:44:08',
                'route' => 'voyager.research-results.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => '题库',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-question',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-01-01 16:48:51',
                'updated_at' => '2019-01-01 16:50:24',
                'route' => 'voyager.questions.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => '班级',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-02-26 19:07:07',
                'updated_at' => '2019-02-26 19:07:24',
                'route' => 'voyager.class.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => '数据图表',
                'url' => '/admin/chart',
                'target' => '_self',
                'icon_class' => 'voyager-pie-chart',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-04-06 14:48:49',
                'updated_at' => '2019-04-06 14:48:57',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}